apiVersion: v1
kind: Pod
metadata:
  name: webserver-nginx
  namespace: playgroud
  labels:
    name: webserver-nginx

spec:
  containers:
  - name: webserver-nginx
    image: nginx:latest
    ports:
      - containerPort: 8081
